[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "gixpes"
version = "0.1.0"
authors = [
    { name="David Capalbo", email="david.capalbo@uni-konstanz.de" }
]
description = ""
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.8"
dependencies = []
